### ISSUE TITLE
Question: Is the search function supposed to search some plugins store?

### ISSUE THREAD

**Issue by Apacelus** [smartfrigde/armcord#124]
In the plugin section there is a search field. Currently it just searches already installed extensions. Is it supposed to search in some plugins store?

Also, where is one generally supposed to find cumcord plugins?

**Comment by lexisother** [comment]
Usually I'd tell you "we aren't Cumcord support", but since I am a maintainer of the project, I can actually help out.

> In the plugin section there is a search field. Currently it just searches already installed extensions. Is it supposed to search in some plugins store?

No, it is not. It is for searching the currently installed set of plugins.

> Also, where is one generally supposed to find cumcord plugins?

There are a couple of places:
- https://dump.cumcord.com - The online plugin store.
- [The Cum Zone](https://cumcordplugins.github.io/Condom/yellowsink.github.io/cc-plugins/cum-zone) - Paste this URL into the plugin installation field for an in-client store.
- The #verified-plugins channel in the Cumcord server: https://discord.com/invite/FhHQQrVs7U

Hope this gives you enough info.
