### ISSUE TITLE
Rich Prescence

### ISSUE THREAD

**Issue by PhoenixOrigin** [smartfrigde/armcord#201]
**Is your feature request related to a problem? Please describe.**
Not really its just cool

**Describe the solution you'd like**
I would like to be able to use rich prescence somehow

**Describe alternatives you've considered**
I don't know any

**Additional context**
Nothing really

**Comment by PoorPocketsMcNewHold** [comment]
Not possible. That's not something that's open and can't be implemented easily as far i know.

**Comment by smartfrigde** [comment]
It was possible with a Cumcord plugin but Discord patched all client mods so you have to wait for websocket reimplenentation which will take ages

**Comment by onkq** [comment]
I'm just gonna come here and say this. You guys don't know what you're taking about.

Yes it's very much possible to create and implement this, it will use the API discord provides, some client mods will also work in the near future. You can check out the pyPresence in more detail if you want. Or CustomRichPresence, it uses pyPresence's features, and uses it in a graphical user interface instead of a python script.

**Comment by smartfrigde** [comment]
Available in latest dev builds.
