### ISSUE TITLE
Cut down on the amount of builds created

### ISSUE THREAD

**Issue by orowith2os** [smartfrigde/armcord#307]
Currently, ArmCord builds (about) 24 packages for macOS, Windows, and Linux. 

The only builds that should be needed on the releases page, at least for Linux, are AppImages, which can then be repackaged into other formats (like RPM). I believe that having all of them shown on the releases page is overwhelming and unneeded.

**Comment by smartfrigde** [comment]
Many people prefer package for their systems package manager and having these packages ready is a good thing, if anyone feels overwhelmed by the downloads list, they can always download from the website or sourceforge

**Comment by Vendicated** [comment]
AppImages are gross and bloated

**Comment by orowith2os** [comment]
> AppImages are gross and bloated

Unrelated to this issue; AppImages can be repackaged into other formats easily, as I'm doing right now with a Flatpak for ArmCord.

My argument for this issue was that end users could download the appropriate formats themselves rather than directly from ArmCord, but I guess ease-of-use wins on that one.

**Comment by Vendicated** [comment]
> AppImages can be repackaged into other formats easily

So you just treat the AppImage as ArmCord binary and package it as a different format? That makes 0 sense because now you're completely ignoring dependency management of whatever format you're using and embedding all dependencies which is exactly what my complaint about AppImages was (and thus related to this issue). This makes no sense and is lazy, you should either properly package it or not pretend to package for it when all you're doing is giving people a wrapped AppImage

**Comment by orowith2os** [comment]
@Vendicated I'm extracting the AppImage and putting the contents into another package format. Multiple packages on Flathub do the same already, and they handle it just fine. Any dependencies needed can be bundled manually if needed, which I doubt needs to be done, as there's already a base application for them.

So no, it's not a wrapped AppImage, just an extracted AppImage in a more efficient (and safer) format.

**Comment by orowith2os** [comment]
I also don't appreciate you insulting me over this topic.

**Comment by kekkodance** [comment]
stop arguing 😭

**Comment by Vendicated** [comment]
If you're just extracting the AppImage and taking some of its contents, then what's the point of even having the intermediate layer of building the AppImage instead of just packing to whatever format immediately? I'm just trying to understand what exactly you're doing

> I also don't appreciate you insulting me over this topic.

I didn't mean to insult you, sorry if you felt that way!

**Comment by orowith2os** [comment]
@Vendicated the packaging is going 

1. download appimage
2. extract the appimage
3. move the binary inside of the appimage into the PATH
4. add a wrapper for that binary for several QOL features, such as PipeWire screenshare

The AppImage building is done here, in ArmCord's GitHub repo.
