### ISSUE TITLE
Support Windows Symlinks with plugins

### ISSUE THREAD

**Issue by Vap0r1ze** [smartfrigde/armcord#311]
I havent had the energy to look back into this but I couldn't use file symlinks on Windows 10 for my Vencord devbuilds (`dist/browser.js`). I could only use hard-links, which kept getting randomly sent to RecycleBin for some reason.

**Comment by Vendicated** [comment]
I think this issue should be moved to the electron repository because this file is being accessed by the chrome extension only (see
https://github.com/Vendicated/Vencord/blob/main/browser/content.js#L6), so it's an electron issue and I doubt ArmCord can fix it. I used hard links as well and haven't had any issues like you, did you disable bundle updates in the settings.json?

**Comment by Vap0r1ze** [comment]
ah yea that makes sense. im not sure if it was bundle updates or esbuild incremental builds, i'll lyk if i try again.
