### ISSUE TITLE
Windows 11: ArmCord no longer sends messages?

### ISSUE THREAD

**Issue by broduer** [smartfrigde/armcord#405]
Close it, just going to uninstall.

**Comment by smartfrigde** [comment]
Can't repro, please send output of console (CTRL+SHIFT+I and click on Console) when trying to send a message

**Comment by broduer40** [comment]
ArmCord 3.2.0
VM206 app:42 [FAST CONNECT] connecting to: wss://gateway.discord.gg/?encoding=json&v=9&compress=zlib-stream
VM206 app:42 [FAST CONNECT] connected in 129ms
VencordWeb:4  Vencord   WebpackInterceptor  Patching webpackChunkdiscord_app.push
31bb213ef464c72c8933.js:5556 [default] [BUILD INFO] Release Channel: stable, Build Number: 204204, Version Hash: 942e9ba3574695cad38c172815bacd0e86ac0d89
31bb213ef464c72c8933.js:3121 AppCrashedFatalReport: getLastCrash not supported.
31bb213ef464c72c8933.js:7 Uncaught (in promise) Error: Cannot find module './notosans-400-normalitalic.woff2'
    at 31bb213ef464c72c8933.js:7:123
    at async Promise.all (index 3)
31bb213ef464c72c8933.js:1450 Deprecation warning: value provided is not in a recognized RFC2822 or ISO format. moment construction falls back to js Date(), which is not reliable across all browsers and versions. Non RFC2822/ISO date formats are discouraged and will be removed in an upcoming major release. Please refer to http://momentjs.com/guides/#/warnings/js-date/ for more info.
Arguments: 
[0] _isAMomentObject: true, _isUTC: false, _useUTC: false, _l: undefined, _i: 5/13/2022 10:00 -0800, _f: undefined, _strict: undefined, _locale: [object Object]
Error
    at Function.createFromInputFallback (https://discord.com/assets/31bb213ef464c72c8933.js:1451:330)
    at Bn (https://discord.com/assets/31bb213ef464c72c8933.js:1477:696)
    at Wn (https://discord.com/assets/31bb213ef464c72c8933.js:1480:356)
    at Zn (https://discord.com/assets/31bb213ef464c72c8933.js:1480:199)
    at Yn (https://discord.com/assets/31bb213ef464c72c8933.js:1479:886)
    at Kn (https://discord.com/assets/31bb213ef464c72c8933.js:1480:697)
    at zn (https://discord.com/assets/31bb213ef464c72c8933.js:1480:731)
    at i (https://discord.com/assets/31bb213ef464c72c8933.js:1447:961)
    at 408481 (https://discord.com/assets/d6cd1d800f4e3b45c9c4.js:21:346)
    at n.<computed> (VencordWeb:193:90)
R @ 31bb213ef464c72c8933.js:1450
31bb213ef464c72c8933.js:10374 [DEPRECATED] Please use `subscribeWithSelector` middleware
(anonymous) @ 31bb213ef464c72c8933.js:10374
31bb213ef464c72c8933.js:5556 [ConnectionStore] Socket is reconnecting because of starting new session
31bb213ef464c72c8933.js:5556 [GatewaySocket] .connect() called, new state is WILL_RECONNECT
31bb213ef464c72c8933.js:5556 [GatewaySocket] Setting connection state to WILL_RECONNECT
31bb213ef464c72c8933.js:5556 [GatewaySocket] Setting connection state to CONNECTING
31bb213ef464c72c8933.js:5556 [GatewaySocket] [CONNECT] wss://gateway.discord.gg, encoding: json, version: 9, compression: zlib-stream
31bb213ef464c72c8933.js:5556 [GatewaySocket] newOrTakeoverWebSocket()
31bb213ef464c72c8933.js:5556 [GatewaySocket] [FAST CONNECT] successfully took over websocket, state: Object
31bb213ef464c72c8933.js:5556 [GatewaySocket] [CONNECTED] wss://gateway.discord.gg/?encoding=json&v=9&compress=zlib-stream in 0 ms
31bb213ef464c72c8933.js:5556 [ConnectionStore] handleIdentify called Object
31bb213ef464c72c8933.js:5556 [GatewaySocket] Setting connection state to IDENTIFYING
31bb213ef464c72c8933.js:5556 [GatewaySocket] [IDENTIFY]
31bb213ef464c72c8933.js:5556 [GatewaySocket] [HELLO] via 
gateway-prd-us-east1-c-9rf1: 0, heartbeat interval: 41250, took 7 ms
31bb213ef464c72c8933.js:5556 [GatewaySocket] [READY] took 656ms, as f9ea6223744139da7e342ff333443eb4 via 
gateway-prd-us-east1-c-9rf1: 355.254
|  id_created: 2.564
|  session_lookup_time: 5.362
|  session_lookup_finished: 0.016
|  discord-sessions-prd-2-230: 327.22
|  |  start_session: 223.909
|  |  |  discord-api-7c89bd68c5-jz86z: 195.374
|  |  |  |  get_user: 16.637
|  |  |  |  get_guilds: 15.944
|  |  |  |  user_settings_proto: 20.579
|  |  |  |  relationships: 94.596
|  |  |  |  friend_suggestion: 0.058
|  |  |  |  connections: 0.101
|  |  |  |  serialized_read_states: 0.008
|  |  |  |  pending_payments: 0.001
|  |  |  |  send_scheduled_deletion_message: 0.002
|  |  |  |  sanitize_premium_perks: 0.001
|  |  |  |  guild_join_requests: 0.001
|  |  |  |  user_guild_settings: 0.002
|  |  |  |  serialized_private_channels: 0.001
|  |  |  |  user_segments: 0.001
|  |  |  |  experiments: 14.118
|  |  |  |  affine_user_ids: 19.797
|  |  |  |  required_action: 0.004
|  |  |  |  authorized_ip_coro: 0.002
|  |  starting_guild_connect: 0.095
|  |  presence_started: 39.233
|  |  guilds_started: 3.08
|  |  guilds_connect: 49.554
|  |  presence_connect: 0.001
|  |  connect_finished: 49.577
|  |  build_ready: 5.801
|  |  clean_ready: 0.001
|  |  optimize_ready: 5.368
|  |  split_ready: 0.154
31bb213ef464c72c8933.js:5556 [GatewaySocket] Setting connection state to SESSION_ESTABLISHED
31bb213ef464c72c8933.js:5556 [Flux] Dispatching CONNECTION_OPEN
31bb213ef464c72c8933.js:5556 [AuthenticationStore] handleConnectionOpen called Object
31bb213ef464c72c8933.js:5556 [DatabaseManager] added association: 621127827504365579 → null
31bb213ef464c72c8933.js:5556 [ConnectionStore] Dispatched 1 messages in 107ms
31bb213ef464c72c8933.js:5556 [GatewaySocket] Updating resume url to wss://gateway-us-east1-c.discord.gg
VencordWeb:4  Vencord   PluginManager  Starting plugin BadgeAPI
VencordWeb:4  Vencord   PluginManager  Starting plugin BetterFolders
VencordWeb:4  Vencord   PluginManager  Starting plugin ConsoleShortcuts
VencordWeb:4  Vencord   PluginManager  Starting plugin EmoteCloner
VencordWeb:4  Vencord   PluginManager  Starting plugin FakeNitro
VencordWeb:4  Vencord   PluginManager  Registering commands of plugin Fart2
VencordWeb:4  Vencord   PluginManager  Starting plugin GameActivityToggle
VencordWeb:4  Vencord   PluginManager  Starting plugin InvisibleChat
VencordWeb:4  Vencord   PluginManager  Starting plugin MessageTags
VencordWeb:4  Vencord   PluginManager  Registering commands of plugin MessageTags
VencordWeb:4  Vencord   PluginManager  Starting plugin MoreUserTags
VencordWeb:4  Vencord   PluginManager  Starting plugin PinDMs
VencordWeb:4  Vencord   PluginManager  Starting plugin PlatformIndicators
VencordWeb:4  Vencord   PluginManager  Starting plugin ReadAllNotificationsButton
VencordWeb:4  Vencord   PluginManager  Starting plugin RelationshipNotifier
VencordWeb:4  Vencord   PluginManager  Starting plugin ReviewDB
VencordWeb:4  Vencord   PluginManager  Starting plugin SearchReply
VencordWeb:4  Vencord   PluginManager  Starting plugin SendTimestamps
VencordWeb:4  Vencord   PluginManager  Starting plugin ServerListIndicators
VencordWeb:4  Vencord   PluginManager  Starting plugin Settings
VencordWeb:4  Vencord   PluginManager  Starting plugin ShikiCodeblocks
VencordWeb:4  Vencord   PluginManager  Registering commands of plugin SilentTyping
VencordWeb:4  Vencord   PluginManager  Registering commands of plugin SupportHelper
VencordWeb:4  Vencord   PluginManager  Starting plugin USRBG
VencordWeb:4  Vencord   PluginManager  Starting plugin ViewIcons
VencordWeb:4  Vencord   PluginManager  Starting plugin WebContextMenus
31bb213ef464c72c8933.js:5556 [GatewaySocket] [READY_SUPPLEMENTAL] took 802ms
31bb213ef464c72c8933.js:5556 [GatewaySocket] Setting connection state to SESSION_ESTABLISHED
31bb213ef464c72c8933.js:5556 [Flux] Slow dispatch on GAMES_DATABASE_UPDATE: 185ms
cdn.discordapp.com/icons/966547980347908128/a_33be8e6b4ae4695f5f1757d699b5357d.png:1          Failed to load resource: the server responded with a status of 404 ()
31bb213ef464c72c8933.js:5556 [ReadStateStore] Deleting ReadState 826689823322013756 0 Object
31bb213ef464c72c8933.js:5556 [MessageActionCreators] Fetching messages for 1110820955095314453 between undefined and undefined. jump={"jumpType":"ANIMATED"}
31bb213ef464c72c8933.js:5556 [MessageActionCreators] Fetched 0 messages from local database (channel_id: 1110820955095314453, remote_fetch_completed: false)
31bb213ef464c72c8933.js:5556 [MessageActionCreators] Fetched 36 messages for 1110820955095314453 isBefore:false isAfter:false
/api/v9/users/@me/notes/920809718509887498:1          Failed to load resource: the server responded with a status of 404 ()
31bb213ef464c72c8933.js:5556 [discord_protos.discord_users.v1.FrecencyUserSettings] Loading proto
31bb213ef464c72c8933.js:7300 Uncaught (in promise) TypeError: Cannot read properties of undefined (reading 'findIndex')
    at UPDATE_VISIBLE_MESSAGES (31bb213ef464c72c8933.js:7300:191)
    at 31bb213ef464c72c8933.js:9759:975
    at 31bb213ef464c72c8933.js:9749:847
    at n (31bb213ef464c72c8933.js:9759:952)
    at t._dispatch (31bb213ef464c72c8933.js:9760:297)
    at 31bb213ef464c72c8933.js:9759:638
    at i.log (31bb213ef464c72c8933.js:9749:786)
    at t._dispatchWithLogging (31bb213ef464c72c8933.js:9759:577)
    at t._dispatchWithDevtools (31bb213ef464c72c8933.js:9759:140)
    at 31bb213ef464c72c8933.js:9758:639
31bb213ef464c72c8933.js:5556 [ClientStateStore] Gap detected in read state versions 87966 87968 Object
31bb213ef464c72c8933.js:5556 [MessageActionCreators] Fetching messages for 880338991101128704 between undefined and undefined. jump={"jumpType":"ANIMATED"}
31bb213ef464c72c8933.js:5556 [MessageActionCreators] Fetched 0 messages from local database (channel_id: 880338991101128704, remote_fetch_completed: false)
/api/v9/users/@me/notes/716329647461236736:1          Failed to load resource: the server responded with a status of 404 ()
31bb213ef464c72c8933.js:5556 [MessageActionCreators] Fetched 33 messages for 880338991101128704 isBefore:false isAfter:false
/api/v9/invites/ZrcMj3Pk?with_counts=true&with_expiration=true:1          Failed to load resource: the server responded with a status of 404 ()
31bb213ef464c72c8933.js:7300 Uncaught (in promise) TypeError: Cannot read properties of undefined (reading 'findIndex')
    at UPDATE_VISIBLE_MESSAGES (31bb213ef464c72c8933.js:7300:191)
    at 31bb213ef464c72c8933.js:9759:975
    at 31bb213ef464c72c8933.js:9749:847
    at n (31bb213ef464c72c8933.js:9759:952)
    at t._dispatch (31bb213ef464c72c8933.js:9760:297)
    at 31bb213ef464c72c8933.js:9759:638
    at i.log (31bb213ef464c72c8933.js:9749:786)
    at t._dispatchWithLogging (31bb213ef464c72c8933.js:9759:577)
    at t._dispatchWithDevtools (31bb213ef464c72c8933.js:9759:140)
    at 31bb213ef464c72c8933.js:9758:639
31bb213ef464c72c8933.js:5556 [MessageQueue] Draining Message Queue with:  Object
31bb213ef464c72c8933.js:5556 [MessageQueue] Skipping message sened because send_fail_100 is enabled
31bb213ef464c72c8933.js:5556 [MessageActionCreators] Failed to send message Object
31bb213ef464c72c8933.js:5556 [Flux] Dispatching MESSAGE_SEND_FAILED
880338991101128704:1 Uncaught (in promise) Object
31bb213ef464c72c8933.js:7300 Uncaught (in promise) TypeError: Cannot read properties of undefined (reading 'findIndex')
    at UPDATE_VISIBLE_MESSAGES (31bb213ef464c72c8933.js:7300:191)
    at 31bb213ef464c72c8933.js:9759:975
    at 31bb213ef464c72c8933.js:9749:847
    at n (31bb213ef464c72c8933.js:9759:952)
    at t._dispatch (31bb213ef464c72c8933.js:9760:297)
    at 31bb213ef464c72c8933.js:9759:638
    at i.log (31bb213ef464c72c8933.js:9749:786)
    at t._dispatchWithLogging (31bb213ef464c72c8933.js:9759:577)
    at t._dispatchWithDevtools (31bb213ef464c72c8933.js:9759:140)
    at 31bb213ef464c72c8933.js:9758:639
31bb213ef464c72c8933.js:3115 Hold Up!
31bb213ef464c72c8933.js:3115 If someone told you to copy/paste something here you have an 11/10 chance you're being scammed.
31bb213ef464c72c8933.js:3115 Pasting anything in here could give attackers access to your Discord account.
DevTools failed to load source map: Could not load content for https://discord.com/assets/ac5a2ca155ef07ea4050.js.map: HTTP error: status code 404, net::ERR_HTTP_RESPONSE_CODE_FAILURE
DevTools failed to load source map: Could not load content for https://discord.com/assets/76151e1de3e89afc2aa9.js.map: HTTP error: status code 404, net::ERR_HTTP_RESPONSE_CODE_FAILURE
DevTools failed to load source map: Could not load content for https://discord.com/assets/5a51d07bf56072c73689.js.map: HTTP error: status code 404, net::ERR_HTTP_RESPONSE_CODE_FAILURE
DevTools failed to load source map: Could not load content for https://discord.com/assets/3a6a179489811c471ed4.js.map: HTTP error: status code 404, net::ERR_HTTP_RESPONSE_CODE_FAILURE
DevTools failed to load source map: Could not load content for https://discord.com/assets/ad682971ad4d096d18f8.js.map: HTTP error: status code 404, net::ERR_HTTP_RESPONSE_CODE_FAILURE
DevTools failed to load source map: Could not load content for https://discord.com/assets/ab3ba843afe020b714ea.js.map: HTTP error: status code 404, net::ERR_HTTP_RESPONSE_CODE_FAILURE
DevTools failed to load source map: Could not load content for https://discord.com/assets/9e6bb3c3c9b41d53d5d7.js.map: HTTP error: status code 404, net::ERR_HTTP_RESPONSE_CODE_FAILURE
DevTools failed to load source map: Could not load content for https://discord.com/assets/0827dd82b9cd8f642252.js.map: HTTP error: status code 404, net::ERR_HTTP_RESPONSE_CODE_FAILURE
DevTools failed to load source map: Could not load content for https://discord.com/assets/2ea27e837665c7a0ecff.js.map: HTTP error: status code 404, net::ERR_HTTP_RESPONSE_CODE_FAILURE
DevTools failed to load source map: Could not load content for https://discord.com/assets/bd55c9111e59c7ac1b54.js.map: HTTP error: status code 404, net::ERR_HTTP_RESPONSE_CODE_FAILURE
DevTools failed to load source map: Could not load content for https://discord.com/assets/d68d46b8b2dbd8de852d.js.map: HTTP error: status code 404, net::ERR_HTTP_RESPONSE_CODE_FAILURE
DevTools failed to load source map: Could not load content for https://discord.com/assets/b93f566acdf0994f7f10.js.map: HTTP error: status code 404, net::ERR_HTTP_RESPONSE_CODE_FAILURE
DevTools failed to load source map: Could not load content for https://discord.com/assets/2c2c763e65eaf938b5dc.js.map: HTTP error: status code 404, net::ERR_HTTP_RESPONSE_CODE_FAILURE
DevTools failed to load source map: Could not load content for https://discord.com/assets/6b772663a5a088167872.js.map: HTTP error: status code 404, net::ERR_HTTP_RESPONSE_CODE_FAILURE
DevTools failed to load source map: Could not load content for https://discord.com/assets/81be9bdfa515643d6d6f.js.map: HTTP error: status code 404, net::ERR_HTTP_RESPONSE_CODE_FAILURE
DevTools failed to load source map: Could not load content for https://discord.com/assets/76bd3919cc711a4f6a8b.js.map: HTTP error: status code 404, net::ERR_HTTP_RESPONSE_CODE_FAILURE
DevTools failed to load source map: Could not load content for https://discord.com/assets/d1dddaf4de8a256b4f68.js.map: HTTP error: status code 404, net::ERR_HTTP_RESPONSE_CODE_FAILURE
DevTools failed to load source map: Could not load content for https://discord.com/assets/31bb213ef464c72c8933.js.map: HTTP error: status code 404, net::ERR_HTTP_RESPONSE_CODE_FAILURE
DevTools failed to load source map: Could not load content for https://discord.com/assets/5abeb4b3219796539333.js.map: HTTP error: status code 404, net::ERR_HTTP_RESPONSE_CODE_FAILURE
DevTools failed to load source map: Could not parse content for https://discord.com/channels/@me/preload.js.map: Unexpected token '<', "<!DOCTYPE "... is not valid JSON
DevTools failed to load source map: Could not parse content for https://discord.com/channels/@me/utils.js.map: Unexpected token '<', "<!DOCTYPE "... is not valid JSON
DevTools failed to load source map: Could not parse content for https://discord.com/channels/@me/titlebar.js.map: Unexpected token '<', "<!DOCTYPE "... is not valid JSON
DevTools failed to load source map: Could not parse content for https://discord.com/channels/@me/bridge.js.map: Unexpected token '<', "<!DOCTYPE "... is not valid JSON
DevTools failed to load source map: Could not load content for https://discord.com/assets/5f75d77b66745b71d04f.js.map: HTTP error: status code 404, net::ERR_HTTP_RESPONSE_CODE_FAILURE
DevTools failed to load source map: Could not parse content for https://discord.com/channels/@me/patch.js.map: Unexpected token '<', "<!DOCTYPE "... is not valid JSON
DevTools failed to load source map: Could not parse content for https://discord.com/channels/@me/mobile.js.map: Unexpected token '<', "<!DOCTYPE "... is not valid JSON
DevTools failed to load source map: Could not load content for https://discord.com/assets/c32cf58dc97b3c280899.js.map: HTTP error: status code 404, net::ERR_HTTP_RESPONSE_CODE_FAILURE
DevTools failed to load source map: Could not parse content for https://discord.com/channels/@me/optimizer.js.map: Unexpected token '<', "<!DOCTYPE "... is not valid JSON
DevTools failed to load source map: Could not load content for https://discord.com/assets/316b1ccd7e8eec54f2cb.js.map: HTTP error: status code 404, net::ERR_HTTP_RESPONSE_CODE_FAILURE
DevTools failed to load source map: Could not load content for https://discord.com/assets/cabeb88084b5de12f69b.js.map: HTTP error: status code 404, net::ERR_HTTP_RESPONSE_CODE_FAILURE
DevTools failed to load source map: Could not load content for https://discord.com/assets/fa1b12e837fdd7157185.js.map: HTTP error: status code 404, net::ERR_HTTP_RESPONSE_CODE_FAILURE
DevTools failed to load source map: Could not load content for https://discord.com/assets/a48ac06ae30799d7d07a.js.map: HTTP error: status code 404, net::ERR_HTTP_RESPONSE_CODE_FAILURE
DevTools failed to load source map: Could not load content for https://discord.com/assets/259854666529ce02ac56.js.map: HTTP error: status code 404, net::ERR_HTTP_RESPONSE_CODE_FAILURE
DevTools failed to load source map: Could not load content for https://discord.com/assets/1c51b31cb4f16e7937b9.js.map: HTTP error: status code 404, net::ERR_HTTP_RESPONSE_CODE_FAILURE
DevTools failed to load source map: Could not load content for https://discord.com/assets/d6cd1d800f4e3b45c9c4.js.map: HTTP error: status code 404, net::ERR_HTTP_RESPONSE_CODE_FAILURE
DevTools failed to load source map: Could not load content for https://discord.com/assets/90c2280b02698c91d2e1.js.map: HTTP error: status code 404, net::ERR_HTTP_RESPONSE_CODE_FAILURE
DevTools failed to load source map: Could not load content for https://discord.com/assets/6ae242f03cfdb7ef841b.js.map: HTTP error: status code 404, net::ERR_HTTP_RESPONSE_CODE_FAILURE
DevTools failed to load source map: Could not load content for https://discord.com/assets/d811cde22d66ff49a6e8.js.map: HTTP error: status code 404, net::ERR_HTTP_RESPONSE_CODE_FAILURE
DevTools failed to load source map: Could not load content for https://discord.com/assets/b9523e6e8153da29f4d8.js.map: HTTP error: status code 404, net::ERR_HTTP_RESPONSE_CODE_FAILURE
DevTools failed to load source map: Could not load content for https://discord.com/assets/ccdc932880fb6c29ada5.js.map: HTTP error: status code 404, net::ERR_HTTP_RESPONSE_CODE_FAILURE
DevTools failed to load source map: Could not load content for https://discord.com/assets/69429efb51d3783f2b1b.js.map: HTTP error: status code 404, net::ERR_HTTP_RESPONSE_CODE_FAILURE
DevTools failed to load source map: Could not load content for https://discord.com/assets/54607aac203925106175.js.map: HTTP error: status code 404, net::ERR_HTTP_RESPONSE_CODE_FAILURE
DevTools failed to load source map: Could not load content for https://discord.com/assets/2718e0bdd6b7ca3087bd.js.map: HTTP error: status code 404, net::ERR_HTTP_RESPONSE_CODE_FAILURE
DevTools failed to load source map: Could not load content for https://discord.com/assets/69581a507e6a5a122225.js.map: HTTP error: status code 404, net::ERR_HTTP_RESPONSE_CODE_FAILURE
DevTools failed to load source map: Could not load content for https://discord.com/assets/69293a10c84424c80d73.js.map: HTTP error: status code 404, net::ERR_HTTP_RESPONSE_CODE_FAILURE
DevTools failed to load source map: Could not load content for https://discord.com/assets/2bca5148146ab09a0f77.js.map: HTTP error: status code 404, net::ERR_HTTP_RESPONSE_CODE_FAILURE
DevTools failed to load source map: Could not load content for https://discord.com/assets/68c45391e9a6c5cce499.js.map: HTTP error: status code 404, net::ERR_HTTP_RESPONSE_CODE_FAILURE
DevTools failed to load source map: Could not load content for https://discord.com/assets/9c02eda6c6d3193f8589.js.map: HTTP error: status code 404, net::ERR_HTTP_RESPONSE_CODE_FAILURE
DevTools failed to load source map: Could not load content for https://discord.com/assets/f9270deeac43b5cec33b.js.map: HTTP error: status code 404, net::ERR_HTTP_RESPONSE_CODE_FAILURE
DevTools failed to load source map: Could not load content for https://discord.com/assets/c58a450ace15698979d5.js.map: HTTP error: status code 404, net::ERR_HTTP_RESPONSE_CODE_FAILURE
DevTools failed to load source map: Could not load content for https://discord.com/assets/e2f6bb841494e43552c3.js.map: HTTP error: status code 404, net::ERR_HTTP_RESPONSE_CODE_FAILURE
DevTools failed to load source map: Could not load content for https://discord.com/assets/f868091ac81bcc228f0b.js.map: HTTP error: status code 404, net::ERR_HTTP_RESPONSE_CODE_FAILURE
DevTools failed to load source map: Could not load content for https://discord.com/assets/99a364b0de21efbfdaf3.js.map: HTTP error: status code 404, net::ERR_HTTP_RESPONSE_CODE_FAILURE
DevTools failed to load source map: Could not load content for https://discord.com/assets/5fd54138c623df023c52.js.map: HTTP error: status code 404, net::ERR_HTTP_RESPONSE_CODE_FAILURE
DevTools failed to load source map: Could not load content for https://discord.com/assets/a178925e38d01d943da9.js.map: HTTP error: status code 404, net::ERR_HTTP_RESPONSE_CODE_FAILURE
DevTools failed to load source map: Could not load content for https://discord.com/assets/da2a6eb7db712adb263d.js.map: HTTP error: status code 404, net::ERR_HTTP_RESPONSE_CODE_FAILURE
DevTools failed to load source map: Could not load content for https://discord.com/assets/d43aeb1ccfc9aada3eb6.js.map: HTTP error: status code 404, net::ERR_HTTP_RESPONSE_CODE_FAILURE
DevTools failed to load source map: Could not load content for https://discord.com/assets/f94246852c0c68721127.js.map: HTTP error: status code 404, net::ERR_HTTP_RESPONSE_CODE_FAILURE
DevTools failed to load source map: Could not load content for https://discord.com/assets/72ac76b9065a4c4c2332.js.map: HTTP error: status code 404, net::ERR_HTTP_RESPONSE_CODE_FAILURE
DevTools failed to load source map: Could not load content for https://discord.com/assets/89c6b10bc7dcb8c1313d.js.map: HTTP error: status code 404, net::ERR_HTTP_RESPONSE_CODE_FAILURE
DevTools failed to load source map: Could not load content for https://discord.com/assets/98f653b527caca6e9458.js.map: HTTP error: status code 404, net::ERR_HTTP_RESPONSE_CODE_FAILURE
DevTools failed to load source map: Could not load content for https://discord.com/assets/fc0fcf68e41ecb06cd97.worker.js.map: Fetch through target failed: Target not supported; Fallback: Unknown error
DevTools failed to load source map: Could not load content for https://discord.com/assets/819.fc0fcf68e41ecb06cd97.worker.js.map: Fetch through target failed: Target not supported; Fallback: Unknown error
DevTools failed to load source map: Could not load content for https://discord.com/assets/3cdf1e508a5821a0cdad.worker.js.map: Fetch through target failed: Target not supported; Fallback: Unknown error
DevTools failed to load source map: Could not load content for https://discord.com/assets/eb003e20b076d1ac1e6c.worker.js.map: Fetch through target failed: Target not supported; Fallback: Unknown error
DevTools failed to load source map: Could not load content for https://discord.com/assets/84f5bda14b25c65f8d7c.worker.js.map: Fetch through target failed: Target not supported; Fallback: Unknown error
3DevTools failed to load source map: Could not load content for https://discord.com/assets/fc0fcf68e41ecb06cd97.worker.js.map: Fetch through target failed: Target not supported; Fallback: Unknown error
31bb213ef464c72c8933.js:7300 Uncaught (in promise) TypeError: Cannot read properties of undefined (reading 'findIndex')
    at UPDATE_VISIBLE_MESSAGES (31bb213ef464c72c8933.js:7300:191)
    at 31bb213ef464c72c8933.js:9759:975
    at 31bb213ef464c72c8933.js:9749:847
    at n (31bb213ef464c72c8933.js:9759:952)
    at t._dispatch (31bb213ef464c72c8933.js:9760:297)
    at 31bb213ef464c72c8933.js:9759:638
    at i.log (31bb213ef464c72c8933.js:9749:786)
    at t._dispatchWithLogging (31bb213ef464c72c8933.js:9759:577)
    at t._dispatchWithDevtools (31bb213ef464c72c8933.js:9759:140)
    at 31bb213ef464c72c8933.js:9758:639
UPDATE_VISIBLE_MESSAGES @ 31bb213ef464c72c8933.js:7300
(anonymous) @ 31bb213ef464c72c8933.js:9759
(anonymous) @ 31bb213ef464c72c8933.js:9749
n @ 31bb213ef464c72c8933.js:9759
t._dispatch @ 31bb213ef464c72c8933.js:9760
(anonymous) @ 31bb213ef464c72c8933.js:9759
i.log @ 31bb213ef464c72c8933.js:9749
t._dispatchWithLogging @ 31bb213ef464c72c8933.js:9759
t._dispatchWithDevtools @ 31bb213ef464c72c8933.js:9759
(anonymous) @ 31bb213ef464c72c8933.js:9758
t.flushWaitQueue @ 31bb213ef464c72c8933.js:9759
(anonymous) @ 31bb213ef464c72c8933.js:9758
t.dispatch @ 31bb213ef464c72c8933.js:9758
A @ 31bb213ef464c72c8933.js:7288
E @ 31bb213ef464c72c8933.js:1217
I @ 31bb213ef464c72c8933.js:1218
y @ 31bb213ef464c72c8933.js:1217
setTimeout (async)
xo @ 31bb213ef464c72c8933.js:1212
y @ 31bb213ef464c72c8933.js:1217
DevTools failed to load source map: Could not load content for https://discord.com/assets/40532.e837c066c1a97d399c69.css.map: HTTP error: status code 404, net::ERR_HTTP_RESPONSE_CODE_FAILURE
31bb213ef464c72c8933.js:3115 Hold Up!
31bb213ef464c72c8933.js:3115 If someone told you to copy/paste something here you have an 11/10 chance you're being scammed.
31bb213ef464c72c8933.js:3115 Pasting anything in here could give attackers access to your Discord account.
31bb213ef464c72c8933.js:3115 Hold Up!
31bb213ef464c72c8933.js:3115 If someone told you to copy/paste something here you have an 11/10 chance you're being scammed.
31bb213ef464c72c8933.js:3115 Pasting anything in here could give attackers access to your Discord account.
31bb213ef464c72c8933.js:3115 Hold Up!
31bb213ef464c72c8933.js:3115 If someone told you to copy/paste something here you have an 11/10 chance you're being scammed.
31bb213ef464c72c8933.js:3115 Pasting anything in here could give attackers access to your Discord account.
31bb213ef464c72c8933.js:3115 Hold Up!
31bb213ef464c72c8933.js:3115 If someone told you to copy/paste something here you have an 11/10 chance you're being scammed.
31bb213ef464c72c8933.js:3115 Pasting anything in here could give attackers access to your Discord account.
31bb213ef464c72c8933.js:3115 Unless you understand exactly what you are doing, close this window and stay safe.
31bb213ef464c72c8933.js:3115 If you do understand exactly what you are doing, you should come work with us https://discord.com/jobs
31bb213ef464c72c8933.js:7300 Uncaught (in promise) TypeError: Cannot read properties of undefined (reading 'findIndex')
    at UPDATE_VISIBLE_MESSAGES (31bb213ef464c72c8933.js:7300:191)
    at 31bb213ef464c72c8933.js:9759:975
    at 31bb213ef464c72c8933.js:9749:847
    at n (31bb213ef464c72c8933.js:9759:952)
    at t._dispatch (31bb213ef464c72c8933.js:9760:297)
    at 31bb213ef464c72c8933.js:9759:638
    at i.log (31bb213ef464c72c8933.js:9749:786)
    at t._dispatchWithLogging (31bb213ef464c72c8933.js:9759:577)
    at t._dispatchWithDevtools (31bb213ef464c72c8933.js:9759:140)
    at 31bb213ef464c72c8933.js:9758:639
UPDATE_VISIBLE_MESSAGES @ 31bb213ef464c72c8933.js:7300
(anonymous) @ 31bb213ef464c72c8933.js:9759
(anonymous) @ 31bb213ef464c72c8933.js:9749
n @ 31bb213ef464c72c8933.js:9759
t._dispatch @ 31bb213ef464c72c8933.js:9760
(anonymous) @ 31bb213ef464c72c8933.js:9759
i.log @ 31bb213ef464c72c8933.js:9749
t._dispatchWithLogging @ 31bb213ef464c72c8933.js:9759
t._dispatchWithDevtools @ 31bb213ef464c72c8933.js:9759
(anonymous) @ 31bb213ef464c72c8933.js:9758
t.flushWaitQueue @ 31bb213ef464c72c8933.js:9759
(anonymous) @ 31bb213ef464c72c8933.js:9758
t.dispatch @ 31bb213ef464c72c8933.js:9758
A @ 31bb213ef464c72c8933.js:7288
E @ 31bb213ef464c72c8933.js:1217
I @ 31bb213ef464c72c8933.js:1218
y @ 31bb213ef464c72c8933.js:1217
setTimeout (async)
xo @ 31bb213ef464c72c8933.js:1212
y @ 31bb213ef464c72c8933.js:1217
setTimeout (async)
xo @ 31bb213ef464c72c8933.js:1212
h @ 31bb213ef464c72c8933.js:1217
T @ 31bb213ef464c72c8933.js:1218
t.setAutomaticAnchor @ WebpackModule584994:2
t.cleanAutomaticAnchor @ WebpackModule584994:2
handleScroll @ WebpackModule584994:2
(anonymous) @ 31bb213ef464c72c8933.js:2811
t.stop @ 31bb213ef464c72c8933.js:2811
t.to @ 31bb213ef464c72c8933.js:2810
s @ 31bb213ef464c72c8933.js:2780
t.scrollTo @ WebpackModule584994:2
t.fixScrollPosition @ WebpackModule584994:2
handleResize @ WebpackModule584994:2
(anonymous) @ 31bb213ef464c72c8933.js:2788
lc @ 31bb213ef464c72c8933.js:1832
t.flushSync @ 31bb213ef464c72c8933.js:1854
(anonymous) @ 31bb213ef464c72c8933.js:2788
eval @ WebpackModule945460:2
eval @ WebpackModule945460:2
31bb213ef464c72c8933.js:7300 Uncaught (in promise) TypeError: Cannot read properties of undefined (reading 'findIndex')
    at UPDATE_VISIBLE_MESSAGES (31bb213ef464c72c8933.js:7300:191)
    at 31bb213ef464c72c8933.js:9759:975
    at 31bb213ef464c72c8933.js:9749:847
    at n (31bb213ef464c72c8933.js:9759:952)
    at t._dispatch (31bb213ef464c72c8933.js:9760:297)
    at 31bb213ef464c72c8933.js:9759:638
    at i.log (31bb213ef464c72c8933.js:9749:786)
    at t._dispatchWithLogging (31bb213ef464c72c8933.js:9759:577)
    at t._dispatchWithDevtools (31bb213ef464c72c8933.js:9759:140)
    at 31bb213ef464c72c8933.js:9758:639


This is off a fresh install, Had uninstalled ArmCord after I kept having this issue.

**Comment by orowith2os** [comment]
@broduer40 move your logs into a gist and edit your message so it's easier to read this issue.
