### ISSUE TITLE
Can't compile under Manjaro ARM

### ISSUE THREAD

**Issue by JeremyStarTM** [smartfrigde/armcord#45]
I am currently running a Raspberry Pi 4B with Manjaro ARM + KDE Plasma. The app runs normally when I enter **npm start**. But when I run **npm run make** to install ArmCord, it fails since it can't find dpkg, what isn't on a normal Arch Linux/Manjaro system because it uses pacman:

```
[jeremystartm@p0rtabl3 armcord]$ npm run make run

> armcord@2.5.0 make
> electron-forge make "run"

✔ Checking your system
✔ Resolving Forge Config

An unhandled rejection has occurred inside Forge:
Error: Cannot make for deb, the following external binaries need to be installed: dpkg, fakeroot
    at MakerDeb.ensureExternalBinariesExist (/home/jeremystartm/GitPrjs/GitHub/smartfrigde/armcord/node_modules/@electron-forge/maker-deb/node_modules/@electron-forge/maker-base/src/Maker.ts:147:13)
    at _default (/home/jeremystartm/GitPrjs/GitHub/smartfrigde/armcord/node_modules/@electron-forge/core/src/api/make.ts:148:11)
    at /home/jeremystartm/GitPrjs/GitHub/smartfrigde/armcord/node_modules/@electron-forge/cli/src/electron-forge-make.ts:44:5

Electron Forge was terminated. Location:
{}
[jeremystartm@p0rtabl3 armcord]$ echo $?
1
```

EDIT: I have fakeroot installed

**Comment by smartfrigde** [comment]
If you are on Arch based distro you can use [Aur package](https://aur.archlinux.org/packages/armcord-bin/). If you want to build from source you can use Electron Forge CLI solution instead of built-in scripts. To do that:
1.Install Electron Forge CLI globally so you can use it in your shell `npm i -g @electron-forge/cli`
2.Make sure you are running latest commit I made which fixes building using CLI ;)
3.Run `electron-forge make --targets @electron-forge/maker-zip`
Alternatively you can also try building Canary branch which has newer/experimental features and has brand new building system (electron builder) which may work normally and without issues out of the box.
If you have any more problems feel free to contact me.

**Comment by JeremyStarTM** [comment]
Thanks, that worked @smartfrigde! Thank you very much!
