### ISSUE TITLE
how to verify releases??

### ISSUE THREAD

**Issue by valtoree** [smartfrigde/armcord#455]
hi
so I got the latest file
ArmCord.Setup.3.2.4.exe
and the latest .yml file
latest.yml from releases pg but how to verify?
I tried sha512 but they do not match, on win power shell.
there's nothing I can see on your github pg how to do it.

certutil -hashfile .\ArmCord.Setup.3.2.4.exe SHA512

help??

**Comment by Vendicated** [comment]
why do you want to verify the hash? it's fairly pointless and the nsis installer likely already does this. if you don't trust the safety of the binaries, just build from source using the instructions in the README

**Comment by valtoree** [comment]
Can I ask why this issue was closed? Can no1 verify the .exe? I can verify the linux appimage but not the .exe.

**Comment by SomeAspy** [comment]
Why bother?
Vendicated makes a valid point.
The hashes for linux and MacOS were not intentional. We are simply dumping the output of the build process into the release. For whatever reason, electron-builder doesn't seem to generate hash files for windows.
In fact, based on download statistics the removal of linux and MacOS hashes is being considered.
