### ISSUE TITLE
When Vencord is enabled, ArmCord settings are inaccessible

### ISSUE THREAD

**Issue by spikespaz** [smartfrigde/armcord#502]
Consider adding a tab to the Discord settings, because when Vencord is installed, it sets the version information at the bottom of the settings window, making ArmCord settings inaccessible.

![image](https://github.com/ArmCord/ArmCord/assets/12502988/f63bf2cc-12d2-45e7-9042-d2cecb296f92)

Additionally, on a fresh install from Nixpkgs, I cannot seem to select "None" for what plugin loader to enable. It spits to the console that it selected `mods: 'vencord',` anyway. I am excusing this as a package issue.

**Comment by odiplol** [comment]
im getting this same issue.

**Comment by Nailington** [comment]
@spikespaz I created https://github.com/ArmCord/ArmCord/issues/491 a bit ago. I just tried turning off VenCord as a mod, but I am still unable to see the settings in ArmCord (getting to the settings pop-up from the tray icon).

Can confirm that it does in fact turn off VenCord, and when opening from a shell says it reports none.
![image](https://github.com/ArmCord/ArmCord/assets/111466491/98627c76-0968-41ba-9793-b7d71e5a21de)
![image](https://github.com/ArmCord/ArmCord/assets/111466491/ba86838a-f35e-445e-b42d-3700abd7250f)


In general it seems like this is an issue for everyone right now, but not everyone notices, since the ArmCord settings isn't needed too often in most use cases (I guess?)

**Comment by spikespaz** [comment]
I'd like to see the ArmCord tabs in Discord's Settings come back, under their own category, without the unicode characters.

**Comment by Nailington** [comment]
I am plainly unable to get to settings from within the client (there was a button down by the versions??? I always just used the dedicated section it adds with the icon next to each option to denote it is from ArmCord). arRPC also doesn't work in my case. It seems that this is a known issue at this point. 

If you need to go to settings, you can from right clicking the tray icon

**Comment by spikespaz** [comment]
Yes I'm aware of the tray icon. I have suggested a closing solution to this issue.

**Comment by pearagit** [comment]
If the tray icon is disabled then there is no way to open settings besides running `window.armcord.openSettingsWindow()` in devtools.
