### ISSUE TITLE
option to restart client from tray context menu

### ISSUE THREAD

**Issue by Ow0cast** [smartfrigde/armcord#532]
**Is your feature request related to a problem? Please describe.**
Sometimes, mic input completely breaks and isn't detected at all, which is fixed by a restart of the app

**Describe the solution you'd like**
Option added to context menu for tray app to restart, instead of having to go into settings menu

**Describe alternatives you've considered**
not really applicable

**Additional context**
Example of new context menu item:
![image](https://github.com/ArmCord/ArmCord/assets/57546895/abb4ec41-da13-4963-a43d-f4f7cf48e823)

**Comment by smartfrigde** [comment]
Since I personally don't really like clogging up the tray icon with options, I added the option to native titlebar menu. There's also a keyboard shortcut CTRL+SHIFT+R for fast hard restart. If it doesn't satisfy you, I'll be looking into tray menu customisation (where you can pick which options you would like to see there)

**Comment by etcowuh** [comment]
awesome! thanks!
