### ISSUE TITLE
FreeBSD binaries

### ISSUE THREAD

**Issue by ERROR-404-NULL-NOT-FOUND** [smartfrigde/armcord#533]
**Is your feature request related to a problem? Please describe.**
Having to manually build Armcord on my FreeBSD system is a bit of a pain

**Describe the solution you'd like**
Provide FreeBSD binaries in the next release

**Comment by SlySven** [comment]
Also the instructions on the front page on how to do the manual build aren't there any more:
> FreeBSD
>
> You can also get ArmCord running on FreeBSD by following [these instructions](https://gist.github.com/txxlchains/4d29c982ac85d5d26f98a51040b5de37).

Maybe https://gist.github.com/axyolotl/4d29c982ac85d5d26f98a51040b5de37 is what is needed?

**Comment by ERROR-404-NULL-NOT-FOUND** [comment]
I was specifically asking for prebuilt binaries in order to install on FreeBSD without having to follow these instructions every time ArmCord updates

**Comment by blcokpl** [comment]
Then don't use FreeBSD 🤪🤪🤪

**Comment by ERROR-404-NULL-NOT-FOUND** [comment]
@blcokpl You could have provided some actually useful information such as "oh, there's a binary here," or "sorry, FreeBSD isn't supported," but instead you decided to send an entirely useless comment to clog up my notification feed with a comment that holds absolutely no value whatsoever

**Comment by smartfrigde** [comment]
![obraz](https://github.com/ArmCord/ArmCord/assets/37928912/aafce4a3-cef2-41e2-8fc1-1d138e43872f)
In theory there's an option to build ArmCord for FreeBSD but in reality [it just produces Linux binary in a `.freebsd` package](https://github.com/electron-userland/electron-builder/issues/4820#issuecomment-950493961). Actual Electron [still doesn't support FreeBSD directly](https://github.com/electron/electron/issues/3797). Since I don't have any knowledge about BSD based systems, I'm not really interested in porting it myself however I'm open to your contributions
