### ISSUE TITLE
[Feature Request] adblock for youtube watchalong

### ISSUE THREAD

**Issue by aya2am** [smartfrigde/armcord#541]
I was wondering if it was possible to intergrate adblock into the app. As it's very annoying to watch youtube ads, trough watchalong feature, for example. Would probably also block more trackers. Probably best with the ability to turn it off. It would be a really nice QoL feature.

**Describe the solution you'd like**
Don't know if this would be possible, as I know barely anything about electron and javascript, but implementing something like this https://github.com/Jense5/electron-ad-blocker, or looking at other implementations like this one https://github.com/th-ch/youtube-music/tree/master/src/plugins/adblocker, if it would be possible to implement any of those into the app.

**Describe alternatives you've considered**
Alternatives are only using a browser, and that misses the point of having a dedicated app like this one.

**Comment by s-liwka** [comment]
This sounds like something that should become a Vencord/Shelter mod and not be directly integrated into ArmCord

**Comment by smartfrigde** [comment]
![obraz](https://github.com/ArmCord/ArmCord/assets/37928912/d3bfcb37-d237-4049-b6eb-3eaf782a01db)
Now with YouTube experimenting with server-side ads, I think a feature like this could be painful to mantain. Especially since blocking YouTube ads is not the main subject of the project. Remember that you can always try loading unpacked Chromium extensions by dropping them in `plugins` folder.

Windows: `%appdata%\ArmCord\plugins`
Linux: `~/.config/ArmCord/plugins`

**Comment by smartfrigde** [comment]
Hi we added this after Discord decided to allow ads in YouTube embeds in chat

https://github.com/ArmCord/ArmCord/commit/8e94ecc1bdb301c626e72c6eba48033109a9681b
