### ISSUE TITLE
Config / Screensharing ➥QUALITY STREAM 

### ISSUE THREAD

**Issue by Elemzir** [smartfrigde/armcord#692]
⛌
- > Thanks for this application.  ArmCord feels and performs well, thanks DEV. //

Every-time I restart ArmCord it forgets my Settings.

⛌
⛌

BUG REPORT 1: Navigating to Settings inside ArmCord and suddenly Settings section has disappeared, 
( ArmCord or VenCord.. mostly both at the same time ).

Quick Solution: Quit ArmCord and then Relaunch, sometimes you'll have to restart twice.

⛌
⛌

BUG REPORT 2: Can't change my Stream Quality.
Even on Nitro channel it forces 720 30fps. ( No option to change quality ).  

⛌
⛌

Attached Images, As Seen Below No Quality Option.

![1](https://github.com/user-attachments/assets/7f095710-740c-4da8-bcd7-31954ca1516e)
![2](https://github.com/user-attachments/assets/01a1b236-9889-4d10-a692-bf92ab30c3b0)

OS: WINDOWS 10 / 11 User

**Comment by SomeAspy** [comment]
Hi, Please use the bug report template, this issue is a mess.
https://github.com/ArmCord/ArmCord/issues/new?assignees=&labels=bug&projects=&template=bug_report.md&title=

regardless, 
Please ensure you are on the latest armcord version, I have no idea what version you are on - this is supposed to be included in the bug report. 

As for settings missing, You most likely are experiencing https://github.com/ArmCord/ArmCord/issues/687
